stages:
  - pre-check
  - build
  - release

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - when: never

include:
  - '.gitlab/ci/pre-check.yml'
  - '.gitlab/ci/build.yml'
  - '.gitlab/ci/release.yml'
