minimum_pre_commit_version: "4.0.0"
default_install_hook_types:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=deActive,DEActive

  - repo: local
    hooks:
      - id: check-copyright
        name: check-copyright
        entry: python3 .gitlab/ci/check_copyright.py
        language: system
        types:
          - go
        require_serial: true
      - id: gofmt
        name: gofmt
        entry: gofmt -w
        language: system
        types:
          - go
        require_serial: true
